import type { ChatUser, ChatMessage, Conversation } from './types';

export const mockUsers: ChatUser[] = [
  {
    id: 'user-1',
    name: 'Mike Johnson',
    email: 'mike.johnson@swifttransport.com',
    phone: '+1 (555) 234-5678',
    company: 'Swift Transport LLC',
    role: 'driver',
    lastMessage: 'Thanks, I\'ll be there in 2 hours',
    lastMessageTime: '2025-01-29T14:32:00Z',
    unreadCount: 0,
    isAIEnabled: true,
    status: 'online',
  },
  {
    id: 'user-2',
    name: 'Sarah Williams',
    email: 'sarah@premiumcarriers.com',
    phone: '+1 (555) 345-6789',
    company: 'Premium Carriers Inc',
    role: 'carrier',
    lastMessage: 'The pickup has been delayed by 1 hour',
    lastMessageTime: '2025-01-29T14:28:00Z',
    unreadCount: 2,
    isAIEnabled: true,
    status: 'online',
  },
  {
    id: 'user-3',
    name: 'Carlos Martinez',
    email: 'carlos.m@fastfreight.com',
    phone: '+1 (555) 456-7890',
    company: 'Fast Freight Co',
    role: 'driver',
    lastMessage: 'GPS signal lost in tunnel area',
    lastMessageTime: '2025-01-29T14:15:00Z',
    unreadCount: 1,
    isAIEnabled: false,
    status: 'away',
  },
  {
    id: 'user-4',
    name: 'Jennifer Lee',
    email: 'jlee@globalbrokers.com',
    phone: '+1 (555) 567-8901',
    company: 'Global Brokers',
    role: 'broker',
    lastMessage: 'Load SD-45821 needs immediate attention',
    lastMessageTime: '2025-01-29T13:45:00Z',
    unreadCount: 0,
    isAIEnabled: true,
    status: 'online',
  },
  {
    id: 'user-5',
    name: 'Robert Chen',
    email: 'rchen@abcshipping.com',
    phone: '+1 (555) 678-9012',
    company: 'ABC Shipping',
    role: 'shipper',
    lastMessage: 'When will my delivery arrive?',
    lastMessageTime: '2025-01-29T13:22:00Z',
    unreadCount: 3,
    isAIEnabled: true,
    status: 'offline',
  },
  {
    id: 'user-6',
    name: 'Amanda Torres',
    email: 'atorres@reliablelogistics.com',
    phone: '+1 (555) 789-0123',
    company: 'Reliable Logistics',
    role: 'carrier',
    lastMessage: 'Driver confirmed for tomorrow pickup',
    lastMessageTime: '2025-01-29T12:55:00Z',
    unreadCount: 0,
    isAIEnabled: true,
    status: 'online',
  },
  {
    id: 'user-7',
    name: 'David Kim',
    email: 'dkim@expressdrivers.com',
    phone: '+1 (555) 890-1234',
    company: 'Express Drivers',
    role: 'driver',
    lastMessage: 'Vehicle breakdown on I-95',
    lastMessageTime: '2025-01-29T12:30:00Z',
    unreadCount: 5,
    isAIEnabled: false,
    status: 'offline',
  },
  {
    id: 'user-8',
    name: 'Lisa Thompson',
    email: 'lisa.t@customerfirst.com',
    phone: '+1 (555) 901-2345',
    company: 'Customer First Inc',
    role: 'customer',
    lastMessage: 'I need to change delivery address',
    lastMessageTime: '2025-01-29T11:45:00Z',
    unreadCount: 1,
    isAIEnabled: true,
    status: 'away',
  },
  {
    id: 'user-9',
    name: 'James Wilson',
    email: 'jwilson@nationalfreight.com',
    phone: '+1 (555) 012-3456',
    company: 'National Freight',
    role: 'broker',
    lastMessage: 'Rate confirmed at $2,450',
    lastMessageTime: '2025-01-29T11:15:00Z',
    unreadCount: 0,
    isAIEnabled: true,
    status: 'online',
  },
  {
    id: 'user-10',
    name: 'Maria Garcia',
    email: 'mgarcia@speedyhaul.com',
    phone: '+1 (555) 123-4567',
    company: 'Speedy Haul',
    role: 'driver',
    lastMessage: 'Delivered successfully, POD attached',
    lastMessageTime: '2025-01-29T10:30:00Z',
    unreadCount: 0,
    isAIEnabled: true,
    status: 'online',
  },
];

export const mockConversations: Record<string, ChatMessage[]> = {
  'user-1': [
    {
      id: 'msg-1-1',
      type: 'system',
      sender: 'system',
      content: 'Conversation started for Load SD-45821',
      timestamp: '2025-01-29T08:00:00Z',
      status: 'delivered',
    },
    {
      id: 'msg-1-2',
      type: 'sms',
      sender: 'ai',
      content: 'Hi Mike! 👋 This is ProStatus AI. You\'re assigned to Load SD-45821 (2024 Tesla Model 3). Pickup at Los Angeles, CA at 10:00 AM. Please confirm you\'re on your way.',
      timestamp: '2025-01-29T08:15:00Z',
      status: 'delivered',
      aiDetails: {
        model: 'Claude Sonnet 4',
        confidenceScore: 0.96,
        tokensUsed: 145,
        wasEdited: false,
      },
    },
    {
      id: 'msg-1-3',
      type: 'sms',
      sender: 'user',
      content: 'Yes, I\'m on my way. Should be there in about 45 minutes.',
      timestamp: '2025-01-29T08:22:00Z',
      status: 'read',
    },
    {
      id: 'msg-1-4',
      type: 'sms',
      sender: 'ai',
      content: 'Great! 🚛 I\'ve updated your ETA to 9:00 AM. The pickup contact is John Smith at (555) 123-4567. Let me know when you arrive!',
      timestamp: '2025-01-29T08:23:00Z',
      status: 'delivered',
      aiDetails: {
        model: 'Claude Sonnet 4',
        confidenceScore: 0.94,
        tokensUsed: 128,
        wasEdited: false,
      },
    },
    {
      id: 'msg-1-5',
      type: 'ai_call',
      sender: 'ai',
      content: 'AI call to confirm pickup completion',
      timestamp: '2025-01-29T10:15:00Z',
      status: 'delivered',
      callDetails: {
        duration: '1:23',
        recordingUrl: '/recordings/call-1-5.mp3',
        transcript: [
          { time: '0:00', speaker: 'AI', text: 'Hi Mike, this is ProStatus checking in. Have you completed the pickup for Load SD-45821?' },
          { time: '0:08', speaker: 'Mike', text: 'Yes, I just picked up the Tesla. Everything looks good.' },
          { time: '0:15', speaker: 'AI', text: 'Excellent! Can you confirm the vehicle condition? Any visible damage?' },
          { time: '0:22', speaker: 'Mike', text: 'No damage, car is in perfect condition. I took photos as required.' },
          { time: '0:30', speaker: 'AI', text: 'Perfect. I\'ve logged the pickup as complete. Your delivery destination is Miami, FL. Safe travels!' },
          { time: '0:40', speaker: 'Mike', text: 'Thanks! I\'ll start heading that way now.' },
        ],
      },
      aiDetails: {
        model: 'GPT-4o',
        confidenceScore: 0.92,
        tokensUsed: 890,
        wasEdited: false,
      },
    },
    {
      id: 'msg-1-6',
      type: 'sms',
      sender: 'ai',
      content: '✅ Pickup confirmed! Load SD-45821 is now in transit to Miami, FL. Estimated delivery: Jan 31 at 2:00 PM. Drive safe! 🛣️',
      timestamp: '2025-01-29T10:20:00Z',
      status: 'delivered',
      aiDetails: {
        model: 'Claude Sonnet 4',
        confidenceScore: 0.98,
        tokensUsed: 95,
        wasEdited: false,
      },
    },
    {
      id: 'msg-1-7',
      type: 'sms',
      sender: 'user',
      content: 'Thanks, I\'ll be there in 2 hours',
      timestamp: '2025-01-29T14:32:00Z',
      status: 'read',
    },
  ],
  'user-2': [
    {
      id: 'msg-2-1',
      type: 'email',
      sender: 'ai',
      subject: 'Load Assignment: SD-45835 - Urgent Pickup Required',
      content: 'Dear Sarah,\n\nWe have a new load assignment that requires immediate attention.\n\nLoad Details:\n- Load ID: SD-45835\n- Vehicle: 2024 BMW X5\n- Pickup: Denver, CO\n- Delivery: Phoenix, AZ\n- Pickup Time: Today at 3:00 PM\n\nPlease confirm driver availability.\n\nBest regards,\nProStatus AI',
      timestamp: '2025-01-29T09:00:00Z',
      status: 'read',
      aiDetails: {
        model: 'Claude Sonnet 4',
        confidenceScore: 0.95,
        tokensUsed: 245,
        wasEdited: false,
      },
    },
    {
      id: 'msg-2-2',
      type: 'email',
      sender: 'user',
      subject: 'Re: Load Assignment: SD-45835 - Urgent Pickup Required',
      content: 'Hi,\n\nWe have Tom available for this pickup. He can be there by 2:30 PM.\n\nThanks,\nSarah',
      timestamp: '2025-01-29T09:45:00Z',
      status: 'read',
    },
    {
      id: 'msg-2-3',
      type: 'sms',
      sender: 'ai',
      content: 'Thanks Sarah! ✅ Tom has been assigned to Load SD-45835. I\'ve sent him the pickup details. ETA to pickup: 2:30 PM.',
      timestamp: '2025-01-29T09:47:00Z',
      status: 'delivered',
      aiDetails: {
        model: 'Claude Sonnet 4',
        confidenceScore: 0.94,
        tokensUsed: 112,
        wasEdited: false,
      },
    },
    {
      id: 'msg-2-4',
      type: 'human_call',
      sender: 'human',
      content: 'Manual call from dispatcher regarding delay',
      timestamp: '2025-01-29T14:00:00Z',
      status: 'delivered',
      callDetails: {
        duration: '3:45',
        transcript: [
          { time: '0:00', speaker: 'Dispatcher', text: 'Hi Sarah, this is Mark from dispatch. I\'m calling about Load SD-45835.' },
          { time: '0:08', speaker: 'Sarah', text: 'Hi Mark, yes I was just about to call you. We have a problem.' },
          { time: '0:15', speaker: 'Dispatcher', text: 'What\'s going on?' },
          { time: '0:18', speaker: 'Sarah', text: 'Tom got stuck in traffic due to an accident on I-70. He\'s going to be about an hour late for pickup.' },
          { time: '0:30', speaker: 'Dispatcher', text: 'Okay, I\'ll notify the shipper. Can he still make the delivery on time?' },
          { time: '0:38', speaker: 'Sarah', text: 'He should be able to if traffic clears up. I\'ll keep you posted.' },
        ],
      },
    },
    {
      id: 'msg-2-5',
      type: 'sms',
      sender: 'user',
      content: 'The pickup has been delayed by 1 hour',
      timestamp: '2025-01-29T14:28:00Z',
      status: 'read',
    },
  ],
  'user-3': [
    {
      id: 'msg-3-1',
      type: 'sms',
      sender: 'ai',
      content: 'Hi Carlos! 🚛 You\'re assigned to Load SD-45840. Pickup at Houston, TX at 11:00 AM. Reply "OK" to confirm.',
      timestamp: '2025-01-29T07:30:00Z',
      status: 'delivered',
      aiDetails: {
        model: 'Claude Sonnet 4',
        confidenceScore: 0.95,
        tokensUsed: 98,
        wasEdited: false,
      },
    },
    {
      id: 'msg-3-2',
      type: 'sms',
      sender: 'user',
      content: 'OK',
      timestamp: '2025-01-29T07:35:00Z',
      status: 'read',
    },
    {
      id: 'msg-3-3',
      type: 'system',
      sender: 'system',
      content: '⚠️ GPS signal lost for Driver Carlos Martinez. Last known location: I-10 West, near mile marker 245.',
      timestamp: '2025-01-29T13:45:00Z',
      status: 'delivered',
    },
    {
      id: 'msg-3-4',
      type: 'ai_call',
      sender: 'ai',
      content: 'Automated call to check driver status',
      timestamp: '2025-01-29T13:50:00Z',
      status: 'failed',
      callDetails: {
        duration: '0:00',
        transcript: [
          { time: '0:00', speaker: 'System', text: 'Call failed - No answer' },
        ],
      },
      aiDetails: {
        model: 'GPT-4o',
        confidenceScore: 0,
        tokensUsed: 0,
        wasEdited: false,
      },
    },
    {
      id: 'msg-3-5',
      type: 'sms',
      sender: 'ai',
      content: '🚨 Carlos, we noticed your GPS went offline. Please call us or reply to confirm you\'re okay. - ProStatus',
      timestamp: '2025-01-29T13:55:00Z',
      status: 'delivered',
      aiDetails: {
        model: 'Claude Sonnet 4',
        confidenceScore: 0.88,
        tokensUsed: 78,
        wasEdited: false,
      },
    },
    {
      id: 'msg-3-6',
      type: 'sms',
      sender: 'user',
      content: 'GPS signal lost in tunnel area',
      timestamp: '2025-01-29T14:15:00Z',
      status: 'read',
    },
  ],
  'user-4': [
    {
      id: 'msg-4-1',
      type: 'email',
      sender: 'ai',
      subject: 'Weekly Load Summary - Global Brokers',
      content: 'Dear Jennifer,\n\nHere\'s your weekly summary:\n\n📊 Loads Completed: 24\n⏱️ On-Time Delivery Rate: 96%\n💰 Total Revenue: $58,400\n\nTop performing routes:\n1. LA → Phoenix: 8 loads\n2. Denver → Dallas: 6 loads\n\nLet me know if you need any details!\n\nBest,\nProStatus AI',
      timestamp: '2025-01-29T08:00:00Z',
      status: 'read',
      aiDetails: {
        model: 'Claude Sonnet 4',
        confidenceScore: 0.97,
        tokensUsed: 320,
        wasEdited: false,
      },
    },
    {
      id: 'msg-4-2',
      type: 'sms',
      sender: 'user',
      content: 'Load SD-45821 needs immediate attention',
      timestamp: '2025-01-29T13:45:00Z',
      status: 'read',
    },
    {
      id: 'msg-4-3',
      type: 'sms',
      sender: 'ai',
      content: 'On it, Jennifer! 🔍 I\'m pulling up the details for Load SD-45821 now. What specific issue are you seeing?',
      timestamp: '2025-01-29T13:46:00Z',
      status: 'delivered',
      aiDetails: {
        model: 'Claude Sonnet 4',
        confidenceScore: 0.91,
        tokensUsed: 85,
        wasEdited: false,
      },
    },
  ],
  'user-5': [
    {
      id: 'msg-5-1',
      type: 'email',
      sender: 'user',
      subject: 'Delivery Status Inquiry',
      content: 'Hello,\n\nI placed an order last week and haven\'t received any updates. Order #ABC-12345.\n\nWhen will my delivery arrive?\n\nRobert Chen',
      timestamp: '2025-01-29T13:00:00Z',
      status: 'read',
    },
    {
      id: 'msg-5-2',
      type: 'email',
      sender: 'ai',
      subject: 'Re: Delivery Status Inquiry',
      content: 'Dear Robert,\n\nThank you for reaching out! I\'ve looked up your order #ABC-12345.\n\n📍 Current Status: In Transit\n🚛 Driver: Mike Johnson\n📅 Estimated Delivery: January 31, 2025 at 2:00 PM\n\nYou can track your delivery in real-time using this link: [Track Delivery]\n\nPlease let me know if you have any other questions!\n\nBest regards,\nProStatus AI',
      timestamp: '2025-01-29T13:05:00Z',
      status: 'delivered',
      aiDetails: {
        model: 'Claude Sonnet 4',
        confidenceScore: 0.96,
        tokensUsed: 278,
        wasEdited: false,
      },
    },
    {
      id: 'msg-5-3',
      type: 'sms',
      sender: 'user',
      content: 'When will my delivery arrive?',
      timestamp: '2025-01-29T13:22:00Z',
      status: 'read',
    },
  ],
  'user-6': [
    {
      id: 'msg-6-1',
      type: 'sms',
      sender: 'ai',
      content: 'Hi Amanda! We have a new load for tomorrow. Load SD-45850: Seattle → Portland. Pickup at 8:00 AM. Can you confirm a driver?',
      timestamp: '2025-01-29T11:00:00Z',
      status: 'delivered',
      aiDetails: {
        model: 'Claude Sonnet 4',
        confidenceScore: 0.94,
        tokensUsed: 102,
        wasEdited: false,
      },
    },
    {
      id: 'msg-6-2',
      type: 'sms',
      sender: 'user',
      content: 'Yes, I have John available. He\'ll be there.',
      timestamp: '2025-01-29T11:15:00Z',
      status: 'read',
    },
    {
      id: 'msg-6-3',
      type: 'sms',
      sender: 'ai',
      content: 'Perfect! ✅ John has been assigned to Load SD-45850. I\'ve sent him all the details. Thanks Amanda!',
      timestamp: '2025-01-29T11:16:00Z',
      status: 'delivered',
      aiDetails: {
        model: 'Claude Sonnet 4',
        confidenceScore: 0.95,
        tokensUsed: 88,
        wasEdited: false,
      },
    },
    {
      id: 'msg-6-4',
      type: 'sms',
      sender: 'user',
      content: 'Driver confirmed for tomorrow pickup',
      timestamp: '2025-01-29T12:55:00Z',
      status: 'read',
    },
  ],
  'user-7': [
    {
      id: 'msg-7-1',
      type: 'sms',
      sender: 'user',
      content: 'Vehicle breakdown on I-95',
      timestamp: '2025-01-29T12:30:00Z',
      status: 'read',
    },
    {
      id: 'msg-7-2',
      type: 'system',
      sender: 'system',
      content: '🚨 URGENT: Driver David Kim reported vehicle breakdown. AI disabled - manual intervention required.',
      timestamp: '2025-01-29T12:31:00Z',
      status: 'delivered',
    },
    {
      id: 'msg-7-3',
      type: 'human_call',
      sender: 'human',
      content: 'Emergency support call',
      timestamp: '2025-01-29T12:35:00Z',
      status: 'delivered',
      callDetails: {
        duration: '5:22',
        transcript: [
          { time: '0:00', speaker: 'Dispatcher', text: 'David, this is dispatch. We got your breakdown alert. Are you safe?' },
          { time: '0:08', speaker: 'David', text: 'Yes, I\'m on the shoulder. The engine just died suddenly.' },
          { time: '0:15', speaker: 'Dispatcher', text: 'Okay, stay in your vehicle. I\'m dispatching roadside assistance now. What\'s your exact mile marker?' },
          { time: '0:25', speaker: 'David', text: 'Mile marker 142, northbound I-95.' },
          { time: '0:32', speaker: 'Dispatcher', text: 'Got it. Help is on the way. ETA about 30 minutes. I\'ll also arrange a backup driver.' },
        ],
      },
    },
  ],
  'user-8': [
    {
      id: 'msg-8-1',
      type: 'sms',
      sender: 'user',
      content: 'I need to change delivery address',
      timestamp: '2025-01-29T11:45:00Z',
      status: 'read',
    },
    {
      id: 'msg-8-2',
      type: 'sms',
      sender: 'ai',
      content: 'Hi Lisa! I can help you update the delivery address. Please provide the new address and I\'ll check if it\'s possible to make the change.',
      timestamp: '2025-01-29T11:46:00Z',
      status: 'delivered',
      aiDetails: {
        model: 'Claude Sonnet 4',
        confidenceScore: 0.93,
        tokensUsed: 95,
        wasEdited: false,
      },
    },
  ],
  'user-9': [
    {
      id: 'msg-9-1',
      type: 'email',
      sender: 'user',
      subject: 'Rate Negotiation - LA to Denver Route',
      content: 'Hi,\n\nWe\'d like to discuss rates for LA to Denver loads. Our current rate is $2,200. Can you do $2,450?\n\nJames Wilson\nNational Freight',
      timestamp: '2025-01-29T10:00:00Z',
      status: 'read',
    },
    {
      id: 'msg-9-2',
      type: 'email',
      sender: 'ai',
      subject: 'Re: Rate Negotiation - LA to Denver Route',
      content: 'Dear James,\n\nThank you for your rate proposal.\n\nBased on current market conditions and our partnership history, I\'m pleased to confirm the rate of $2,450 for LA to Denver loads.\n\nThis rate will be effective for the next 30 days.\n\nPlease let me know if you\'d like to proceed!\n\nBest regards,\nProStatus AI',
      timestamp: '2025-01-29T10:15:00Z',
      status: 'delivered',
      aiDetails: {
        model: 'Claude Sonnet 4',
        confidenceScore: 0.89,
        tokensUsed: 198,
        wasEdited: true,
      },
    },
    {
      id: 'msg-9-3',
      type: 'sms',
      sender: 'user',
      content: 'Rate confirmed at $2,450',
      timestamp: '2025-01-29T11:15:00Z',
      status: 'read',
    },
  ],
  'user-10': [
    {
      id: 'msg-10-1',
      type: 'sms',
      sender: 'ai',
      content: 'Hi Maria! Load SD-45815 delivery to Tampa, FL. Please confirm when you arrive.',
      timestamp: '2025-01-29T09:00:00Z',
      status: 'delivered',
      aiDetails: {
        model: 'Claude Sonnet 4',
        confidenceScore: 0.96,
        tokensUsed: 72,
        wasEdited: false,
      },
    },
    {
      id: 'msg-10-2',
      type: 'sms',
      sender: 'user',
      content: 'Just arrived at delivery location',
      timestamp: '2025-01-29T10:15:00Z',
      status: 'read',
    },
    {
      id: 'msg-10-3',
      type: 'ai_call',
      sender: 'ai',
      content: 'Delivery confirmation call',
      timestamp: '2025-01-29T10:20:00Z',
      status: 'delivered',
      callDetails: {
        duration: '0:45',
        transcript: [
          { time: '0:00', speaker: 'AI', text: 'Hi Maria, confirming you\'ve arrived for delivery. Is the receiver ready?' },
          { time: '0:08', speaker: 'Maria', text: 'Yes, they\'re unloading now.' },
          { time: '0:15', speaker: 'AI', text: 'Great! Please get a signature on the POD. Have a great day!' },
        ],
      },
      aiDetails: {
        model: 'GPT-4o',
        confidenceScore: 0.94,
        tokensUsed: 320,
        wasEdited: false,
      },
    },
    {
      id: 'msg-10-4',
      type: 'audio',
      sender: 'user',
      content: 'Voice memo confirming delivery completion',
      timestamp: '2025-01-29T10:28:00Z',
      status: 'read',
      attachments: [
        { type: 'audio', name: 'delivery_confirmation.mp3', url: '/audio/delivery_confirmation.mp3' },
      ],
    },
    {
      id: 'msg-10-5',
      type: 'sms',
      sender: 'user',
      content: 'Delivered successfully, POD attached',
      timestamp: '2025-01-29T10:30:00Z',
      status: 'read',
      attachments: [
        { type: 'image', name: 'POD_SD45815.jpg', url: '/images/pod.jpg' },
      ],
    },
    {
      id: 'msg-10-6',
      type: 'sms',
      sender: 'ai',
      content: '🎉 Excellent work Maria! Delivery confirmed and POD logged. Load SD-45815 marked as complete. Thank you!',
      timestamp: '2025-01-29T10:31:00Z',
      status: 'delivered',
      aiDetails: {
        model: 'Claude Sonnet 4',
        confidenceScore: 0.98,
        tokensUsed: 82,
        wasEdited: false,
      },
    },
  ],
};
